# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e906c9336d9464809eb04159a554be1a77f55ab073365f3cce3868a7166653cc5836d82a5c51984422c00a632f06fa4a0d134b532af644c536c12e7168d51b27

test:
  secret_key_base: c523c8c16ed0488a35a77558bd3395cb623975eaba6f3832c732d7a0fdb774a3f9125df195dc908cab1aca595830c6381a011786816d8eaf802e568751fec66d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
